// ── MUTABLE STATE ─────────────────────────────────────────────

let tkSeq = 100, spSeq = 1, nextId = 8, colorIdx = 7, pendingColor = 0;
let dragId = null, subDragId = null;

// ── SEED DATA ─────────────────────────────────────────────────

let projects = [
  {
    id:1, name:'Comedy 4 All', color:0, stage:'inprogress',
    githubRepo: knownGithubRepoForName('Comedy 4 All'),
    desc:'comedy4all.com · v10 · Supabase + Stripe',
    goal:'500 paying subscribers at $12/month.',
    subStages:[{id:'ss1',label:'Idea'},{id:'ss2',label:'Writing'},{id:'ss3',label:'In development'},{id:'ss4',label:'Testing'},{id:'ss5',label:'Live'}],
    subProjects:[
      mkSubP('Feature film concept','Early conversations about a stand-up documentary','ss1'),
      mkSubP('New hour — joke editing','Refining existing material for next hour','ss3'),
      mkSubP('Sitcom pilot','Fleshing out characters and premise','ss2'),
      mkSubP('Brooks AI v2','Next version of the AI writing assistant','ss3'),
    ],
    openSubBoard:false,
    convo:{Goal:'Monetize via Stripe subscriptions.',Ideas:'Dark mode, Brooks AI, Show History done.',Financing:'$12/mo Stripe plan.',Marketing:'',Team:'',Timeline:'',Risks:'',['Action items']:''},
    tickets:[
      mkTk('Set up Stripe subscriptions','todo','high'),
      mkTk('Add joke export PDF','todo','med'),
      mkTk('Fix dark mode emoji','inprogress','high'),
      mkTk('Deploy v10','done','med'),
    ],
    contacts:[{name:'Ryan Glomboske',role:'Co-founder',email:'',phone:'',type:'team',notes:''}],
    finances:[
      {id:'f1',desc:'Stripe subscription revenue',type:'revenue',amount:0,status:'projected'},
      {id:'f2',desc:'Anthropic API costs',type:'expense',amount:50,status:'monthly'},
    ],
    people:[{name:'Ryan Glomboske',perm:'editor',visible:true}],
    openTab:null,
  },
  {
    id:2, name:'SipSavvy.ai', color:1, stage:'inprogress',
    githubRepo: knownGithubRepoForName('SipSavvy.ai'),
    desc:'AI sommelier SaaS for restaurants',
    goal:'Sign first 10 paying restaurant clients.',
    subStages:[{id:'ss1',label:'Prospect'},{id:'ss2',label:'Outreach'},{id:'ss3',label:'Demo'},{id:'ss4',label:'Negotiating'},{id:'ss5',label:'Closed'}],
    subProjects:[
      mkSubP('DFW upscale restaurant list','Target 50 restaurants in Dallas/Fort Worth','ss1'),
      mkSubP('Toast integration build','POS integration with Toast','ss2'),
    ],
    openSubBoard:false,
    convo:{Goal:'Land first paying restaurant clients.',Ideas:'Toast + Oracle MICROS integrations.',Financing:'SaaS pricing TBD.',Marketing:'Sales pitch done.',Team:'',Timeline:'',Risks:'',['Action items']:''},
    tickets:[
      mkTk('Build Toast POS integration','todo','high'),
      mkTk('Launch outreach to 20 restaurants','todo','high'),
      mkTk('Finalize pricing tiers','inprogress','med'),
      mkTk('Complete sales pitch deck','done','low'),
    ],
    contacts:[{name:'Ryan Glomboske',role:'Technical Partner',email:'',phone:'',type:'partner',notes:'NDA signed.'}],
    finances:[
      {id:'f3',desc:'Monthly SaaS per restaurant',type:'revenue',amount:299,status:'projected'},
      {id:'f4',desc:'Dev & hosting',type:'expense',amount:120,status:'monthly'},
    ],
    people:[{name:'Ryan Glomboske',perm:'editor',visible:true}],
    openTab:null,
  },
  {
    id:3, name:'Aria', color:2, stage:'plan',
    githubRepo: knownGithubRepoForName('Aria'),
    desc:'React PWA personal assistant · Vercel',
    goal:'Central hub for all projects.',
    subStages:[{id:'ss1',label:'Idea'},{id:'ss2',label:'Building'},{id:'ss3',label:'Done'}],
    subProjects:[
      mkSubP('Voice input module','Push-to-talk or wake word','ss1'),
      mkSubP('Google Calendar sync','Two-way calendar integration','ss1'),
    ],
    openSubBoard:false,
    convo:{Goal:'Integrate with all projects + voice.',Ideas:'Live weather + sports done.',Financing:'',Marketing:'',Team:'',Timeline:'',Risks:'Scope creep.',['Action items']:''},
    tickets:[
      mkTk('Add voice input','todo','med'),
      mkTk('Google Calendar sync','todo','med'),
      mkTk('Live weather widget','done','low'),
    ],
    contacts:[],finances:[],people:[],openTab:null,
  },
  {
    id:4, name:'Plan-It Travel', color:3, stage:'initiate',
    githubRepo: knownGithubRepoForName('Plan-It Travel'),
    desc:'Next.js constraint-based trip solver',
    goal:'Public beta with real flight data.',
    subStages:[{id:'ss1',label:'Idea'},{id:'ss2',label:'Building'},{id:'ss3',label:'Testing'},{id:'ss4',label:'Live'}],
    subProjects:[mkSubP('Flight API research','Find Amadeus replacement','ss1')],
    openSubBoard:false,
    convo:{Goal:'Constraint-based trip planning.',Ideas:'Mock flight data working.',Financing:'',Marketing:'',Team:'',Timeline:'',Risks:'Amadeus API dropped.',['Action items']:''},
    tickets:[
      mkTk('Find replacement flight API','todo','high'),
      mkTk('Build auth layer','todo','med'),
      mkTk('Onboarding flow','done','med'),
    ],
    contacts:[],finances:[],people:[],openTab:null,
  },
  {
    id:5, name:'FanHole (FLY)', color:4, stage:'evaluate',
    githubRepo: knownGithubRepoForName('FanHole (FLY)'),
    desc:'Sports venue discovery platform',
    goal:'Close $2.5M seed round.',
    subStages:[{id:'ss1',label:'Concept'},{id:'ss2',label:'Building'},{id:'ss3',label:'Investor ready'},{id:'ss4',label:'Funded'}],
    subProjects:[
      mkSubP('Seed pitch deck','Investor presentation','ss2'),
      mkSubP('Equity agreement final','Legal docs for all founders','ss1'),
    ],
    openSubBoard:false,
    convo:{Goal:'$100M exit via sports venue discovery.',Ideas:'Dashboard prototype built.',Financing:'$2.5M seed at 15-20%. $5K from David.',Marketing:'',Team:'Sean, Ryan, David.',Timeline:'',Risks:'Competitive market.',['Action items']:''},
    tickets:[
      mkTk('Build investor pitch deck','todo','high'),
      mkTk('Finalize equity agreements','todo','high'),
      mkTk('Venue owner dashboard','done','med'),
      mkTk('React prototype','done','low'),
    ],
    contacts:[
      {name:'Sean Sawyer',role:'Head Engineer',email:'',phone:'',type:'team',notes:'30% equity.'},
      {name:'Ryan Glomboske',role:'Technical',email:'',phone:'',type:'team',notes:'20% equity.'},
      {name:'David Sinkkinin',role:'Investor',email:'',phone:'',type:'investor',notes:'$5K · 10% equity.'},
    ],
    finances:[
      {id:'f5',desc:'David Sinkkinin investment',type:'investment',amount:5000,status:'received'},
      {id:'f6',desc:'Seed round target',type:'investment',amount:2500000,status:'projected'},
    ],
    people:[
      {name:'Sean Sawyer',perm:'editor',visible:true},
      {name:'Ryan Glomboske',perm:'editor',visible:true},
      {name:'David Sinkkinin',perm:'viewer',visible:false},
    ],
    openTab:null,
  },
  {
    id:6, name:'Find My Peeps', color:5, stage:'idea',
    githubRepo: knownGithubRepoForName('Find My Peeps'),
    desc:'DFW underrepresented biz discovery',
    goal:'Go-to directory for DFW.',
    subStages:[{id:'ss1',label:'Idea'},{id:'ss2',label:'Validate'},{id:'ss3',label:'Build'},{id:'ss4',label:'Launch'}],
    subProjects:[mkSubP('Concept validation interviews','Talk to 10 DFW business owners','ss1')],
    openSubBoard:false,
    convo:{Goal:'Discoverable directory for underrepresented DFW businesses.',Ideas:'HTML prototype only.',Financing:'',Marketing:'',Team:'',Timeline:'',Risks:'',['Action items']:''},
    tickets:[mkTk('Validate concept with 10 interviews','todo','med')],
    contacts:[],finances:[],people:[],openTab:null,
  },
  {
    id:7, name:'Vantage', color:6, stage:'plan',
    githubRepo: knownGithubRepoForName('Vantage'),
    desc:'Entrepreneurial OS — see everything at once',
    goal:'Launch as a SaaS product for entrepreneurs.',
    subStages:[{id:'ss1',label:'Idea'},{id:'ss2',label:'Design'},{id:'ss3',label:'Build'},{id:'ss4',label:'Beta'},{id:'ss5',label:'Launch'}],
    subProjects:[
      mkSubP('MVP feature spec','Define exactly what ships in v1','ss2'),
      mkSubP('Competitor research','Notion, Linear, Basecamp analysis','ss2'),
      mkSubP('Brand identity','Logo, colors, type system','ss1'),
      mkSubP('Beta tester outreach','Find 5 entrepreneur early users','ss1'),
    ],
    openSubBoard:false,
    convo:{
      Goal:'Build the go-to OS for entrepreneurs.',
      Ideas:'Pipeline · tickets · contacts · finances · conversation · sub-whiteboards.',
      Financing:'SaaS subscription TBD.',
      Marketing:'Target: serial entrepreneurs.',
      Team:"Michael D'Asaro (founder).",
      Timeline:'Plan → Evaluate → Initiate.',
      Risks:'Scope creep. Crowded market.',
      ['Action items']:'Define MVP\nEvaluate tech stack\nFind 5 beta testers\nResearch competitors',
    },
    tickets:[
      mkTk('Define Vantage MVP feature set','todo','high'),
      mkTk('Research competitors','todo','high'),
      mkTk('Evaluate standalone tech stack','todo','high'),
      mkTk('Find 5 entrepreneur beta testers','todo','med'),
      mkTk('Design brand identity','todo','med'),
      mkTk('Sub-whiteboard feature','done','high'),
      mkTk('Pipeline drag-and-drop','done','high'),
      mkTk('Per-project ticket system','done','high'),
      mkTk('Contacts & finances layer','done','med'),
      mkTk('Name the product','done','low'),
    ],
    contacts:[{name:"Michael D'Asaro",role:'Founder',email:'',phone:'',type:'team',notes:'1996 Olympian. Serial entrepreneur.'}],
    finances:[],people:[],openTab:null,
  },
];
